### ISSUE TITLE
`data-view-transition` interferes with `data-on-click`

### ISSUE THREAD

**Issue by CiberNin** [starfederation/datastar#19]
### Description

When I add the `data-view-transition` attribute to a div element, it appears to interfere with the functioning of the `data-on-click` attribute. This issue is observable as JavaScript errors in the console on page load, and the expected backend message is not sent when the element is clicked.

The console displays the following error on page load, and clicking the div does not trigger any backend communication:

```plaintext
VM1159:5 Uncaught ReferenceError: sample is not defined
  at eval (eval at <anonymous> (core.ts:215:26), <anonymous>:5:3)
  at Object.onLoad (visibility.ts:154:16)
  at core.ts:223:29
  at walkDownDOM (core.ts:265:5)
  at walkDownDOM (core.ts:270:12)
  at walkDownDOM (core.ts:270:12)
  at core.ts:92:12
  at Array.forEach (<anonymous>)
  at applyPlugins (core.ts:91:18)
  at run (core.ts:66:10)
```

### Code Snippet

Here is the portion of the template causing the issue:

```html
<div
  id="stuff"
  style="width:min-content"
  data-view-transition="sample-transition"
  data-on-click="$$get('/{{connector.machine_id}}/{{ file_name }}/watch')"
>
</div>
```

### Additional Information

I'm attempting to implement a sliding animation on click, using the following CSS animations inspired by the HTMX site's view transition example:

```css
@keyframes fade-in {
  from { opacity: 0; }
}

@keyframes fade-out {
  to { opacity: 0; }
}

@keyframes slide-from-right {
  from { transform: translateX(90px); }
}

@keyframes slide-to-left {
  to { transform: translateX(-90px); }
}

/* Define animations for the old and new content */
::view-transition-old(slide-it) {
  animation: 180ms cubic-bezier(0.4, 0, 1, 1) both fade-out,
             600ms cubic-bezier(0.4, 0, 0.2, 1) both slide-to-left;
}

::view-transition-new(slide-it) {
  animation: 420ms cubic-bezier(0, 0, 0.2, 1) 90ms both fade-in,
             600ms cubic-bezier(0.4, 0, 0.2, 1) both slide-from-right;
}

/* Tie the view transition to a given CSS class */
.sample-transition {
  view-transition-name: slide-it;
}
```

Any insights or suggestions on resolving this conflict would be greatly appreciated.
Together I hope we can _delve_ into the solution to this issue.
