### ISSUE TITLE
Python SDK Packages Missing Framework Adapters

### ISSUE THREAD

**Issue by craigjperry2** [starfederation/datastar#890]
### Bug Report

The “datastar-py” source in the GitHub repository contains convenient streaming response adapters for various frameworks which add in the SSE headers. Those adapters are not published in the library on pypi.

It’s easy enough to vendor the functionality into my app but it’d be cool if those little adapters could come over in the published sdk lib too.

### Datastar Version

V0.4.3

**Comment by gazpachoking** [comment]
Those will be published in the next python SDK version, we are a bit behind on pypi releases at the moment though. You can source the dep directly from github to use them in the mean time. This is how you'd do it with uv, there is a similar method for poetry.
```toml
[tool.uv.sources]
datastar-py = { git = "https://github.com/starfederation/datastar", subdirectory = "sdk/python"}
```
